set TOP_LEVEL_NAME "tb"
cd top/sim/mentor
source msim_setup.tcl ;# script generated by qsys for setting up simulation
vlog -sv ../../../tb.sv  ;# compile testbench
ld_debug  ;# compile and elaborate testbench
onfinish {stop}
log -r *
run -all
set failed [expr [coverage attribute -name TESTSTATUS -concise] > 1]
exit -code ${failed}
